config/routes.rb
require 'sidekiq/web'
# Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_token]
# Sidekiq::Web.set :sessions, Rails.application.config.session_options

Rails.application.routes.draw do

  constraints AdminAccess do
    mount Sidekiq::Web => '/sidekiq'
    mount Flipper::UI.app(Flipper) => '/flipper'
    mount Blazer::Engine => '/blazer'
  end

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  root to: 'home#index'

  get 'search', to: 'search#index'
  get 'search_preview', to: 'search_previews#index'
  get 'torso-comparison', to: 'static_product_comparisons#show'

  resources :gift_cards do
    get 'print'
    resources :payments, module: 'gift_cards'
  end

  resources :enquiries
  resource :subscriptions

  get 'feeds.xml', to: 'feeds#index'
  get 'feeds/google_shopping'
  get 'feeds/sitemap'

  resources :products, path: 'p' do
    resources :order_items, module: 'products'
  end

  resources :categories, path: 'c'

  resource :checkout, controller: 'checkout' do
    resource :servicepoints, module: 'checkout'
    resources :order_items, module: 'checkout'
    resources :orders, module: 'checkout' do
      resource :acceptance, module: 'orders', controller: 'acceptance'
      resource :payments, module: 'orders'
      resource :gift_cards, module: 'orders'
      resource :vouchers, module: 'orders'
      resource :share_links, module: 'orders'
      resource :duplicates, module: 'orders'
    end
  end

  resource :users

  resources :orders do
    get :payment
    resource :customs_invoices, module: 'orders'
    resource :invoices, module: 'orders'
  end

  namespace :shiphero do
    post 'webhooks/inventory_update', to: 'webhooks#inventory_update'
    post 'webhooks/shipment_update', to: 'webhooks#shipment_update'
    post 'webhooks/order_canceled', to: 'webhooks#order_canceled'
  end

  namespace :admin do
    resource :product_sales
    resource :translations
    resource :image_uploads
    resource :s3_signatures
    resource :positions
    resource :bulk, controller: 'bulk'
    resources :purchase_orders
    resources :translation_changes
    resources :featured_products
    resources :featured_categories
    resources :shipping_times
    resources :manufacturers
    resources :categories do
      resources :category_banners
      resources :category_megaimages
    end
    resources :pages do
      resources :page_banners
    end
    resources :timeline_events
    resources :users
    resources :campaigns
    resources :vouchers
    resources :notices
    resources :gift_cards
    resources :markets
    resources :delivery_methods

    resources :products do
      post :destroy_datasheet
      resources :product_photos
      resource :duplicates, module: 'products'
    end

    resources :orders do
      resources :order_items
      resource :shipments
      resources :invoices
      resource :confirmations
      resource :duplicates
      resource :cancellations
      resource :review
      resource :payments, module: 'orders'
    end

  end

  resources :categories

  resource :product_comparisons

  get '/produkter/:category/:product', to: 'legacy_url#product'
  get '/produkter/:category', to: 'legacy_url#category'

  resources :pages, path: ''


  get '*path' => 'application#not_found' if Rails.env.production?

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/models/gift_card.rb
class GiftCard < ApplicationRecord
  include FileUploader[:invoice_file]
  include FileUploader[:file]

  has_many :gift_card_transactions
  has_many :orders, through: :gift_card_transactions
  has_one :invoice, dependent: :destroy
  before_create :set_code, :set_expiry, :set_card_number, :set_rate_and_vat

  scope :not_expired, -> { where('expires_at > ?', DateTime.now) }
  scope :active, -> { paid.not_expired }

  enum status: {
    unpaid: 0,
    paid: 1,
    used: 2
  }

  alias_attribute :order_number, :card_number

  def market
    Market.fetch(market_id)
  end

  def payment_method
    'credit_card'
  end

  def net_amount_in_cents
    (net_amount * 100).to_i
  end

  def net_used
    gift_card_transactions.map(&:net_amount).inject(:+) || 0
  end

  def net_available
    net_amount - net_used || 0
  end

  def gross_amount
    Currency.calculate_base(net_amount, rate, vat)
  end

  def net_amount
    super || 0
  end

  def ensure_status!
    self.used! unless net_available > 0
  end

  def accounting_class
    super ? super.constantize : market.accounting_class
  end

  private

  def set_code
    self.code = SecureRandom.hex(4)
  end

  def set_expiry
    self.expires_at = 3.years.from_now
  end

  def set_card_number
    self.card_number = GiftCardNumber.next unless self.card_number
  end

  def set_card_number!
    self.update card_number: GiftCardNumber.next
  end

  def set_rate_and_vat
    self.rate = market.rate
    self.vat = market.vat
  end

  def set_accounting_class
    self.accounting_class = market.accounting_class
  end

end

app/controllers/admin/gift_cards_controller.rb
class Admin::GiftCardsController < AdminController

  def index
    @gift_cards = GiftCard.all
  end

  def show
    @gift_card = GiftCard.find params[:id]
  end

  private


  def authorize
    authorize! :update, GiftCard
  end


end

app/controllers/checkout/orders/gift_cards_controller.rb
class Checkout::Orders::GiftCardsController < ApplicationController

  def create
    @order = Order.find params[:order_id]
    @gift_card = GiftCard.find_by(code: params[:gift_card][:code])

    if @gift_card
      @order.update! gift_card: @gift_card
      redirect_to [:new, :checkout, :order], notice: t('.success')
    else
      flash[:alert] = t('.not_found')
      redirect_to [:new, :checkout, :order]
    end

  end

end

app/controllers/gift_cards/payments_controller.rb
class GiftCards::PaymentsController < ApplicationController

  def index
    @gift_card = GiftCard.find(params[:gift_card_id])

    if @gift_card.unpaid?
      GiftCards::Paid.call(gift_card: @gift_card, payment_id: params[:txnid])
    end

    redirect_to @gift_card
  end

end

app/controllers/gift_cards_controller.rb
class GiftCardsController < ApplicationController

  def new
    @gift_card = GiftCard.new
  end

  def show
    @gift_card = GiftCard.find params[:id]
  end

  def download
    @gift_card = GiftCard.find params[:gift_card_id]
    send_data(@gift_card.file.read, filename: 'gavekort.pdf', type: 'application/pdf')
  end

  def create
    @gift_card = GiftCard.new(params[:gift_card].permit(:name, :email, :net_amount, :recipient, :message))
    @gift_card.status = :unpaid
    @gift_card.market_id = context.market.key
    @gift_card.save!

    accepturl = gift_card_payments_url(@gift_card)

    render json: {
      paymentwindow: Billing.new(@gift_card).payment_params(accepturl, capture: true)
    }

  end

end

app/helpers/admin/gift_cards_helper.rb
module Admin::GiftCardsHelper
end

app/helpers/checkout/orders/gift_cards_helper.rb
module Checkout::Orders::GiftCardsHelper
end

app/helpers/gift_cards/payments_helper.rb
module GiftCards::PaymentsHelper
end

app/helpers/gift_cards_helper.rb
module GiftCardsHelper
end

app/views/gift_cards/_gift_grid.html.slim
.product-grid-item.mb-6.text-center
  = link_to new_gift_card_path, class: 'border hover--shadow-md relative block text-black no-underline grid-item rounded-sm h-full flex flex-col'
    .flex.text-xs.mx-2.h-5.uppercase.items-center
    .flex.flex-col.flex-grow
      .h-32.md--h-64.flex.align-center.justify-center.mb-4.px-6
        = image_tag('icons/gift_icon.svg')
      .h-5
      .flex.flex-col.flex-grow.justify-between.bg-grey-lightest.px-6
        .text-sm.my-6.overflow-hidden.leading-normal.h-11.text-ellipsis
          = t 'gift_cards.new.text'
        div.flex-grow.uppercase.font-bold
          span = t 'gift_cards.new.title'

app/views/gift_cards/_pdf.html.erb
<!DOCTYPE html>
<html>
  <head>
    <style>
.gift-card {
  text-align: center;
  font-family: 'Times new roman';
  font-size: 14px;
}
.header {
  max-width: 100%;
  margin: 20px 0;
}
.title {
  font-size: 50px;
  margin: 10px 0;
  text-transform: uppercase;
  font-weight: 200;
}
.message {
  font-size: 20px;
  font-style: italic;
}
.code {
  font-size: 20px;
}
.value {
  font-size: 50px;
  margin: 30px 0;
}
hr {
  margin: 20px 0;
  border: 1px solid #ccc;
}
    </style>
  </head>
  <body>
    <div class="gift-card">
      <%= image_tag 'https://www.eanatomi.dk/gift_card/eanatomi.png' %>
      <%= image_tag 'https://www.eanatomi.dk/gift_card/header.png', class: 'header' %>
      <h1 class="title"><%= t('.title') %></h1>
      <p class="message"><%= gift_card.message %></p>
      <hr>
      <p>
        <strong><%= t('.code', code: gift_card.code) %><br>
        <%= t('.valid_from', date: l(gift_card.created_at, format: '%e %B %Y')) %></strong>
      </p>
      <p class="value"><%= number_to_currency gift_card.net_amount %></p>
      <hr>
      <p>
        <%= t('.welcome') %>
      </p>
      <%= simple_format t('.terms') %>
      <p>
        <strong><%= t('.usage') %><br>
        <%= t('.vat') %></strong>
      </p>
      <hr>
      <p><%= t('.address') %></p>
    </div>
  </body>
</html>

app/views/gift_cards/_print.html.erb
<!DOCTYPE html>
<html>
  <head>
    <style>
.gift-card {
  text-align: center;
  font-family: 'Times new roman';
  font-size: 14px;
}
.header {
  max-width: 100%;
  margin: 20px 0;
}
.title {
  font-size: 50px;
  margin: 10px 0;
  text-transform: uppercase;
  font-weight: 200;
}
.message {
  font-size: 20px;
  font-style: italic;
}
.code {
  font-size: 20px;
}
.value {
  font-size: 50px;
  margin: 30px 0;
}
hr {
  margin: 20px 0;
  border: 1px solid #ccc;
}
    </style>
  </head>
  <body>
    <div class="gift-card">
      <%= image_tag image_url('gift_card/eanatomi.png') %>
      <%= image_tag image_url('gift_card/header.png'), class: 'header' %>
      <h1 class="title">Gavekort</h1>
      <p class="message"><%= @gift_card.message %></p>
      <hr>
      <p>
        <strong>Gavekortets indløsningskode: <span class="code"><%= @gift_card.code %></span><br>
        Udstedt den <%= l @gift_card.created_at, format: '%e %B %Y' %> med værdi:</strong>
      </p>
      <p class="value"><%= number_to_currency @gift_card.net_amount %></p>
      <hr>
      <p>
        Vi ser frem til at byde dig velkommen på www.eAnatomi.dk.
      </p>
      <p>
        Betingelser:<br>
        Gavekortet kan kun bruges til køb af varer, for gavekortets værdi, fra sortimentet som findes på www.eanatomi.dk. Gavekortet skal bruges indenfor 3 år. Sker dette ikke mister gavekortet sin værdi.<br>
        Køb foretaget med brug af gavekortet er underlagt eanatomi.dk’s gældende handelsbetingelser.
      </p>

      <p>
        <strong>Ved bestilling på eAnatomi.dk indtastes gavekortets kode<br>
        Gavekortets beløb er inkl. moms.</strong>
      </p>
      <hr>
      <p>eAnatomi – Tlf.: +45 2991 9911 – E-mail:   info@eanatomi.dk  – www.eAnatomi.dk</p>
    </div>
  </body>
</html>

app/views/gift_cards/new.html.slim
.flex.flex-col-reverse.md--flex-row
  / .hidden.md--block.w-layout-side.flex-no-shrink
  /   = render 'sidebar'
  div.bg-white.w-full
    = image_tag 'header.jpg', class: 'img-responsive w-full'
.container.flex.flex-col-reverse.md--flex-row.my-10
  .m-8.w-full
    h1.pl-4.mb-10.font-alt = t '.title'
    = form_for @gift_card, html: { role: 'new-giftcard-form', 'data-remote' => true, 'novalidate' => true } do |f|
      div.my-4
        label.block.mb-2.pl-4  = t '.name'
        = f.text_field :name, class: 'form-control rounded-full py-4', required: true
      div.my-4
        label.block.mb-2.pl-4  = t '.email'
        = f.text_field :email, class: 'form-control rounded-full py-4', required: true
      div.my-4
        label.block.mb-2.pl-4  = t '.recipient'
        = f.text_field :recipient, class: 'form-control rounded-full py-4', required: true
      div.my-4
        label.block.mb-2.pl-4  = t '.amount'
        = f.text_field :net_amount, class: 'form-control rounded-full py-4', required: true
      div.my-4
        label.block.mb-2.pl-4  = t '.message'
        = f.text_field :message, class: 'form-control rounded-full py-4'

      button.btn.btn-green.rounded-full.px-6.py-4.mt-10 type='submit' = t '.pay'

app/views/gift_cards/show.html.slim
.container.text-center
  i.fa.fa-check-circle.fa-state-success.fa-4x
  h1 = t('.thanks', name: @gift_card.name)
  br
  p = link_to t('.download'), @gift_card.file.url(download: true), target: '_blank', class: 'btn btn-success btn-lg'